name: Update JSON File

on:
  push:
    branches:
      - main

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update JSON File
        env: # Or as an environment variable
          API_SECRET: ${{ secrets.API_SECRET }}

        run: |
          curl -sSL -H "Authorization: Bearer $API_SECRET" \
               -H "Accept: application/vnd.github.v3.raw" \
               -o groupData.json \
               https://raw.githubusercontent.com/Project-Exoduss/google-maps/main/groupData.json

          node ../index.cjs

          # Commit changes
          git config user.email "maxevans3108@gmail.com"
          git config user.name "max-carver"
          git add groupData.json
          git commit -m "Update JSON file"
          git push
